// GENERATED FILE. Do not edit.
//
// The one retriever, emitted by scripts/site/ask_retrieval.py, which is where the reasoning
// and the tests live. The browser lane gets the same source inlined into the page. Two copies
// that agree today is the failure this repo keeps relearning, so neither is hand written and
// `python3 scripts/site/ask_retrieval.py --self-test` goes red when they drift.
//
// Regenerate with:
//
//   python3 scripts/site/ask_retrieval.py --write-worker

/* ---------------------------------------------------------------- shared retriever
   Generated by scripts/site/ask_retrieval.py. Do not edit in place: it is embedded in the
   page AND in the worker, and a hand edit to one of them is the two lanes disagreeing about
   which decision a question is about. */
function askTokens(s) {
  return String(s == null ? "" : s).toLowerCase()
    .replace(/[^a-z0-9 ]+/g, " ").split(/\s+/).filter(Boolean);
}

/* THE DOCUMENT IS THE WHOLE DECISION, not just its title. Everything a reader might remember
   about it goes in: what it is called, what it says, who decided it, where it is, what it is
   filed under. A field they half remember is the field they will type. */
function askDoc(it) {
  return [it.title, it.summary, it.decider, (it.counties || []).join(" "),
          String(it.topic || "").replace(/-/g, " "), it.status].filter(Boolean).join(" ");
}

/* Built once per page load, not per keystroke. 69 decisions of a few hundred words each is a
   few milliseconds; doing it on every character is what made the previous scorer visible on a
   mid range phone. */
function askIndex(items) {
  var docs = [], df = {}, total = 0;
  items.forEach(function (it) {
    var tf = {}, n = 0;
    askTokens(askDoc(it)).forEach(function (w) {
      if (w.length < 2) return;
      tf[w] = (tf[w] || 0) + 1; n += 1;
    });
    Object.keys(tf).forEach(function (w) { df[w] = (df[w] || 0) + 1; });
    docs.push({ id: it.id, tf: tf, len: n });
    total += n;
  });
  return { docs: docs, df: df, N: docs.length || 1,
           avg: docs.length ? total / docs.length : 1 };
}

/* BM25. `idf` is the Robertson form with the +1 that keeps a term appearing in EVERY document
   at zero rather than negative: a word every decision uses says nothing about which one is
   meant, and a negative score would actively push the right answer down. */
/* The frame of a question, dropped from the QUERY and never from the documents. The reasoning,
   which is long and is not a reader's to download, is in scripts/site/ask_retrieval.py under
   THE FRAME OF A QUESTION. Short version: IDF cannot tell "how" from a rare topical word, and
   "how" is in nearly every question a person types. "may" is absent because it is a month. */
var askFrame = new Set(("what which who whom whose when where why how whether " +
  "is are was were be been being am do does did done doing " +
  "can could will would shall should must ought " +
  "have has had having " +
  "the and but for nor yet so than that this these those there here " +
  "about above across after against along among around before behind below beneath beside " +
  "between beyond during except from inside into near onto outside over through throughout " +
  "under underneath until upon with within without " +
  "all any both each either few many more most much neither none once only other some such " +
  "her hers him his its our ours she her their theirs them they you your yours mine my " +
  "tell tells told say says said know knows get gets got give gives show shows " +
  "want wants need needs please thanks thank hello " +
  "anything something everything nothing anyone someone everyone " +
  "just also very really still even ever never always").split(" "));

function askBm25(idx, query) {
  var qs = askTokens(query).filter(function (w) {
    return w.length > 2 && !askFrame.has(w);
  });
  if (!qs.length) return [];
  var out = [];
  idx.docs.forEach(function (d) {
    /* WHAT MATCHED, NOT ONLY HOW WELL. A score alone cannot tell one repeated common word from
       two independent rare ones, and those mean completely different things about whether the
       reader meant this decision. `terms` counts DISTINCT query words present and `rarest` is
       the smallest document frequency among them, so a caller can insist on corroboration
       rather than on a number that both cases can reach. */
    var s = 0, terms = 0, rarest = Infinity;
    qs.forEach(function (w) {
      var f = d.tf[w] || 0;
      if (!f) return;
      var n = idx.df[w] || 0;
      var idf = Math.log(1 + (idx.N - n + 0.5) / (n + 0.5));
      s += idf * (f * (1.2 + 1)) / (f + 1.2 * (1 - 0.75 + 0.75 * (d.len / idx.avg)));
      /* ONLY A DISCRIMINATING WORD CORROBORATES. Counting every match made "best way to train
         for a marathon" look corroborated, because "best", "way" and "for" are all in a record
         about anything. A word most decisions use cannot be evidence for one of them, and the
         threshold is the corpus's own, so it never needs a stopword list somebody maintains. */
      if (idf >= 1.0) terms += 1;
      if (n && n < rarest) rarest = n;
    });
    if (s > 0) out.push({ id: d.id, score: s, terms: terms,
                          rarest: rarest === Infinity ? 0 : rarest });
  });
  out.sort(function (a, b) { return b.score - a.score || (a.id < b.id ? -1 : 1); });
  return out;
}

/* RECIPROCAL RANK FUSION. Each list contributes 1/(k + rank) for whatever it ranked, so a
   decision both lists like beats one that either loves. Magnitudes are discarded on purpose:
   see the note in ask_retrieval.py about adding scores from unrelated scales. */
function askFuse(lists) {
  var acc = {};
  lists.forEach(function (list) {
    (list || []).forEach(function (row, i) {
      var id = row && row.id;
      if (!id) return;
      acc[id] = (acc[id] || 0) + 1 / (60 + i + 1);
    });
  });
  return Object.keys(acc).map(function (id) { return { id: id, score: acc[id] }; })
    .sort(function (a, b) { return b.score - a.score || (a.id < b.id ? -1 : 1); });
}

export { askTokens, askDoc, askIndex, askBm25, askFuse, askFrame };
